name: Simple Cx CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CI: true
  NODE_ENV: production

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-v0-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v0-cache-

      - name: Install dependencies
        run: yarn install --immutable

      - name: EsLint
        run: yarn run lint

      - name: Jest
        run: yarn run jest --collectCoverage --runInBand

      - name: Types
        run: yarn run type

      - name: Build
        run: yarn run build

